cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views
app_name = 'coupons'

urlpatterns=[
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('myadminpage/'), admin.site.urls),
    path(_('cart'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupon'), include('coupons.urls', namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'order'
urlpatterns=[
    path(_('create/'), views.order_create, name='order_create'),
    path(_('admin/order/<int:order_id>/'), views.admin_order_detail, name='admin_order_detail'),
    path(_('admin/order/<int:order_id>/pdf'), views.admin_order_pdf, name ='admin_order_pdf')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns= [
    path('', views.product_list_view, name='product_list'),
    path('<slug:category_slug>/', views.product_list_view, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail_view, name='product_detail')
]

cart/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity =  forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    override = forms.BooleanField(required=False, initial=False, widget= forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.contrib import messages
from shop.models import Product
from .cart import Cart
from coupons.forms import CouponApplyForm
from .forms import CartAddProductForm
from django.utils.safestring import mark_safe
# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
        url = reverse("shop:product_list")
        message = mark_safe(f'Product added to cart successfully. <a href="{url}">Continue Shopping</a>')
        messages.success(request, message)
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id =product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail_view(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True})
    coupon_apply_form = CouponApplyForm()
    return render(request,'cart/detail.html', {'cart':cart, 'coupon_apply_form':coupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Your Shopping Cart | {{ block.super }}{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="m-3">Your shopping cart</h1>
    <div class="row">

      <div class="col-12">
        <div class="table-responsive">

          <table class="table cart table-striped">
            <thead class="text-light">
              <tr class="bg-primary">
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart %}
              {% with product=item.product %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    <img class="img-thumbnail" src="{% if product.image %}{{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                  </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                  <form class="form" action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" name="" value="Update" class="btn-primary">
                    {% csrf_token %}
                  </form>
                </td>
                <td>
                  <form method="post" action="{% url 'cart:cart_remove' product.id %}">
                    {% csrf_token %}
                    <input type="submit" name="" value="Remove" class="btn-primary">
                  </form>
                </td>
                <td class="text-right">${{ item.price }}</td>
                <td class="text-right">${{ item.total_price }}</td>
              </tr>
              {% endwith %}
              {% endfor %}
              {% if cart.coupon %}
                <tr>
                  <td>Subtotal</td>
                  <td colspan='4'></td>
                  <td class='num'>${{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
                <tr>
                  <td>
                    "{{ cart.coupon.code }}" coupon
                    ({{ cart.coupon.discount }}% off)
                  </td>
                  <td colspan='4'></td>
                  <td class='num neg text-danger'>- ${{ cart.get_discount|floatformat:2 }}</td>
                </tr>
              {% endif %}
              <tr class="total">
                <td>Total</td>
                <td colspan='4'></td>
                <td class='num'>${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
              </tr>
            </tbody>
          </table>
          <p>Appy a coupon:</p>
          <form action="{% url 'coupons:apply' %}" method="post">
            {% for field in coupon_apply_form  %}
              {{ field.label }}
              {{ field }}
              <input class="btn btn-primary" type="submit" name="" value="Apply">
              {% for error in field.errors %}
                <div class="text-danger">
                  {{ error }}
                </div>
              {% endfor %}
            {% csrf_token %}
            {% endfor %}
          </form>
        </div>
        <p class="text-right">
          <a href="{% url 'shop:product_list' %}" class="btn btn-light">Continue shopping</a>
          <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
        </p>
      </div>

    </div>


  </div>
{% endblock %}