cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('myadminpage/'), admin.site.urls),
    path(_('cart'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupon'), include('coupons.urls', namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns= [
    path('', views.product_list_view, name='product_list'),
    path('<slug:category_slug>/', views.product_list_view, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail_view, name='product_detail')
]

shop/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering =('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete= models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=300, db_index =True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

# Create your views here.
def product_list_view(request,  category_slug=None):
    category=None
    categories=Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category':category, 'categories': categories, 'products':products})


def product_detail_view(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    try:
        related = Product.objects.filter(category=product.category).exclude(id=product.id)
    except Product.DoesNotExist:
        pass
    cart_product_form = CartAddProductForm()
    context = {'product':product,'cart_product_form':cart_product_form, 'related':related}
    return render(request, 'shop/product/detail.html',context)

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{{ product.name }} | {{ block.super }}{% endblock %}
{% block content %}
<div class=" container text-justify">
    <div class="row mt-5">
      <div class="col-9">
        <div class="row mb-5">
          <div class="col-8">
            <img class=" img-thumbnail" style="width:40rem;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }} image">
          </div>
          <div class="col-4">
            <h1>{{ product.name }}</h1>
            <h3>
              <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
            </h3>
            <h3 class="price">${{ product.price }}</h3>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              {% csrf_token %}
              {{ cart_product_form }}
              <input class="btn btn-primary" type="submit" value="{% trans "Add to cart" %}">
            </form>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="pills-description-tab" data-toggle="pill" href="#pills-description" role="tab" aria-controls="pills-description" aria-selected="true">Description</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Features</a>
              </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade show active" id="pills-description" role="tabpanel" aria-labelledby="pills-description-tab"><p>{{ product.description|linebreaks }}</p></div>
              <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
            </div>
          </div>
        </div>
      </div>
      <!--<div class="col-1">
      </div>-->
      <div class="col-3">
        <h2>{% trans "Related Products" %}</h2>
        {% for item in related %}
          <div class="col-8">
            <img class="card-img" src="{% if item.image %}{{ item.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ item.name }} image">
            <p><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></p>
          </div>
        {% endfor %}
      </div>
    </div>

</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}{% if category %}{{ category.name }} | {{ block.super }} {% else %} Products | {{block.super}}{% endif %}{% endblock %}
{% block content %}
  <div class="row">
    <div class=" col-3 mt-5 ml-2">
      {% if categories %}
        <h4 class="mb-4">Categories</h4>
        <ul class="list-group ">
            <a href="{% url 'shop:product_list' %}" class="list-group-item-action">
              <li class="list-group-item {% if not category %}active{% endif %} ">
                All
              </li>
            </a>
          {% for c in categories %}
              <a class="list-group-item-action" href="{{ c.get_absolute_url }}">
                <li class="list-group-item {% if category.slug == c.slug %}active{% endif %} ">
                  {{ c.name }}
                </li>
              </a>
          {% endfor %}
        </ul>
      {% else %}
        <h3>There are no product categories in this shop</h3>
      {% endif %}
    </div>

    <div class="mt-5 col-8">
      {% if products or category %}
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        <div class="row">
          {% for product in products %}
              <div class="col-sm-4 mb-4">
                <a href="{{ product.get_absolute_url }}">
                  <div class="card">
                    <div class="text-center px-20 py-10">
                        <img class="card-img-top" src="{% if product.image %}{{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }} image">
                        <div class="card-body">
                          <a class="card-title" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                          <p class="card-text">${{ product.price }}</p>
                        </div>
                    </div>
                  </div>
                </a>
              </div>
          {% endfor %}
        </div>
      {% else %}
        <p>There are no products listed in this shop.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}